name: Build Desktop Executable
on: [push]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Fixed from node-size to node-version!

      - name: Install dependencies and Build Exe
        run: |
          npm install
          npm run package
