name: Build Desktop Executable
on: [push] # This tells GitHub to build it every time you update your repo

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install dependencies and Build Exe
        run: |
          npm install
          npm run package

      - name: Upload Executable to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: AuditDiff-Windows-App
          path: dist/
